# Generated by Django 5.1.7 on 2025-05-23 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(max_length=100)),
                ('ubicacion_mapa', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('tamano', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('foto_url', models.URLField()),
                ('disponible', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centroadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perro')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perro')),
            ],
            options={
                'unique_together': {('usuario', 'perro')},
            },
        ),
    ]
