# Generated by Django 5.2.3 on 2025-07-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perro',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to='api.centroadopcion'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perro'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perro'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'perro')},
        ),
    ]
