# Generated by Django 5.1.7 on 2025-05-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to='api.centroadopcion'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamano',
            field=models.CharField(max_length=50),
        ),
    ]
