# Generated by Django 5.1.7 on 2025-05-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perro_estado_salud_alter_perro_centro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='Estadodesalud',
            field=models.CharField(default='Saludable', max_length=100),
            preserve_default=False,
        ),
    ]
