# Generated by Django 5.1.7 on 2025-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perro_estadodesalud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Estadodesalud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
