# Generated by Django 5.1.7 on 2025-05-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_perro_estadodesalud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='Estadodesalud',
        ),
    ]
